export const NOTIFICATION_TYPE_EMPTY_INVENTORY =
  'NOTIFICATION_TYPE_EMPTY_INVENTORY';
export const NOTIFICATION_TYPE_LOW_INVENTORY =
  'NOTIFICATION_TYPE_LOW_INVENTORY';
export const NOTIFICATION_TYPE_HIGH_INVENTORY =
  'NOTIFICATION_TYPE_HIGH_INVENTORY';
