//initialization
export const RECEIVE_SHOPS = 'RECEIVE_SHOPS';

//Web socket action
export const WEBSOCKET_INVENTORY_CHANGE = 'WEBSOCKET:INVENTORY_CHANGE';

//Filters Action - constant
export const VisibilityFilters = {
    SHOW_FULL_STOCK: 'SHOW_FULL_STOCK',
    SHOW_LOW_ON_STOCK: 'SHOW_LOW_ON_STOCK',
    SHOW_NO_STOCK: 'SHOW_NO_STOCK',
    SHOW_ALL: 'SHOW_ALL'
};
export const SET_VISIBILITY_FILTER_STORE_STAT = 'SET_VISIBILITY_FILTER_STORE_STAT';
export const SET_VISIBILITY_FILTER_STORE_NAME = 'SET_VISIBILITY_FILTER_STORE_NAME';

//Transfer
export const SET_STORE_FROM_TO = 'SET_STORE_FROM_TO';
export const SET_SHOE_FROM_TO = 'SET_SHOE_FROM_TO';
export const SET_TRANSFER_VALIDITY = 'SET_TRANSFER_VALIDITY';
export const DO_TRANSFER = 'DO_TRANSFER';
export const SET_QUANTITY = 'SET_QUANTITY';
export const TRANSFER_RESET = 'TRANSFER_RESET';








